### ISSUE TITLE
unite dark and light syntax

### ISSUE THREAD

**Issue by pbraga** [simurai/duotone-syntax#1]
I would like to request the union of the light a dark syntax duotone in a single syntax thta matches the theme (light or dark). Similar to atom-monokai (https://atom.io/themes/atom-monokai).

Thank you

**Comment by simurai** [comment]
I see.. a united duotone theme would adapt to if the UI theme is light or dark.

One issue is that syntax themes _should_ include a [styles/syntax-variables.less](https://github.com/simurai/duotone-syntax/blob/master/styles/syntax-variables.less) file so that other packages can use the colors. Some themes override that file on disk. I tried to add different color schemes a while back https://github.com/simurai/duotone-dark-syntax/pull/4, but closed it later again.

Is the reason so you only have to switch one theme and not both UI and Syntax theme? Using a package like https://atom.io/packages/theme-toggler could help. Then in the settings you can set between which themes it should toggle.

**Comment by pbraga** [comment]
Yes the idea is the syntax following the ui between dark and light, again like atom-monokai. But your explanation and suggestion are spot on, thank you.
